const attributeRegex = {
  title: /\btitle="(.*?)"/,
  vuePath: /\bvue="(.*?)"/,
  htmlPath: /\bhtml="(.*?)"/,
  reactPath: /\breact\s*=\s*["'](.*?)["']/,
  sveltePath: /\bsvelte="(.*?)"/,
  solidPath: /\bsolid="(.*?)"/,
  preactPath: /\bpreact="(.*?)"/,
  description: /\bdescription="(.*?)"/,
  order: /\border="(.*?)"/,
  select: /\bselect="(.*?)"/,
  github: /\bgithub="(.*?)"/,
  gitlab: /\bgitlab="(.*?)"/,
  stackblitz: /\bstackblitz="(.*?)"/,
  codesandbox: /\bcodesandbox="(.*?)"/,
  scope: /\bscope="(.*?)"/,
  vueFiles: /\bvueFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  reactFiles: /\breactFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  svelteFiles: /\bsvelteFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  solidFiles: /\bsolidFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  preactFiles: /\bpreactFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  htmlFiles: /\bhtmlFiles=("\{((.|\n)*?)\}"|"\[((.|\n)*?)\]")/,
  ssg: /\bssg="(.*?)"/,
  htmlWriteWay: /\bhtmlWriteWay="(.*?)"/,
  background: /\bbackground="(.*?)"/,
  playground: /\bplayground="(.*?)"/,
};

const getAttribute = (content: string, regex: RegExp) =>
  content.match(regex)?.[1];

export const parsePreviewAttributes = (content: string) => ({
  title: getAttribute(content, attributeRegex.title) || '',
  vuePath: getAttribute(content, attributeRegex.vuePath),
  htmlPath: getAttribute(content, attributeRegex.htmlPath),
  reactPath: getAttribute(content, attributeRegex.reactPath),
  sveltePath: getAttribute(content, attributeRegex.sveltePath),
  solidPath: getAttribute(content, attributeRegex.solidPath),
  preactPath: getAttribute(content, attributeRegex.preactPath),
  description: getAttribute(content, attributeRegex.description) || '',
  order: getAttribute(content, attributeRegex.order),
  select: getAttribute(content, attributeRegex.select),
  github: getAttribute(content, attributeRegex.github) || '',
  gitlab: getAttribute(content, attributeRegex.gitlab) || '',
  stackblitz: getAttribute(content, attributeRegex.stackblitz),
  codesandbox: getAttribute(content, attributeRegex.codesandbox),
  scope: getAttribute(content, attributeRegex.scope) || '',
  vueFiles: getAttribute(content, attributeRegex.vueFiles),
  reactFiles: getAttribute(content, attributeRegex.reactFiles),
  svelteFiles: getAttribute(content, attributeRegex.svelteFiles),
  solidFiles: getAttribute(content, attributeRegex.solidFiles),
  preactFiles: getAttribute(content, attributeRegex.preactFiles),
  htmlFiles: getAttribute(content, attributeRegex.htmlFiles),
  ssg: !!getAttribute(content, attributeRegex.ssg),
  htmlWriteWay: getAttribute(content, attributeRegex.htmlWriteWay) || 'write',
  background: getAttribute(content, attributeRegex.background),
  playground: getAttribute(content, attributeRegex.playground),
});

export type PreviewAttributes = ReturnType<typeof parsePreviewAttributes>;
